### ISSUE TITLE
Empty?

### ISSUE THREAD

**Issue by fwarmuth** [meyerjo/MultiModalContrastiveLearning#1]
Hey,
Found your repo in an interesting paper, Improving Unimodal Object Recognition with Multimodal Contrastive  Learning.
Wonder when or if the code will be published?

regards

**Comment by meyerjo** [comment]
Hey, thanks for the inquiry. We are currently working on preparing this repository. I hope that, we can publish our code by end of the month, early february.

**Comment by fwarmuth** [comment]
any progress?
